### ISSUE TITLE
OpenTnsNamesFile cannot be used due to TnsNamesFileInfo constructor being internal.

### ISSUE THREAD

**Issue by salixzs** [espenrl/TnsNames#1]
If I want to pass in existing tnsnames.ora file and not use ResolveRootTnsNamesFiles() method to get TnsNames, then it is impossible as I cannot create parameter of type TnsNamesFileInfo.

Either empty public constructor should exist or existing should be made public.

Thank You!

**Comment by espenrl** [comment]
Hi, I will look into this. I have a new upcoming version where source code for the ANTLR runtime is embedded, so no dll dependency on ANTLR.
