### ISSUE TITLE
Incorrect usage of FileStream object - may lead to memory leaks

### ISSUE THREAD

**Issue by salixzs** [espenrl/TnsNames#4]
FileStream object is IDisposable object and suggested always to use with using() {}.
See  https://msdn.microsoft.com/en-us/library/47ek66wy(v=vs.110).aspx

In TnsNames.cs, method OpenTnsNamesFile, FileStream object is used simply be new-ing it.
Correct usage would be
```
TnsNamesParser parser = null;
using (fileStream = new FileStream(tnsNamesFileInfo.Filepath, FileMode.Open))
{
            var inputStream = new AntlrInputStream(fileStream);
            var lexer = new TnsNamesLexer(inputStream);
            var commonTokenStream = new CommonTokenStream(lexer);
            parser = new TnsNamesParser(commonTokenStream);
}
```

Is it possible to address this issue and previous problem (public constructor) and to make new version of NuGet package ASAP, please.

**Comment by espenrl** [comment]
I can't promise anything, but maybe next week (earliest).

**Comment by salixzs** [comment]
Thanks. I really appreciate Your work and contribution.
